### ISSUE TITLE
WinForms app installed on system disk exception.

### ISSUE THREAD

**Issue by sanyandreichuk** [microsoft/appcenter-sdk-dotnet#1084]
### **Description**

AppCenter for WinForms is working fine when an app is run from VS, but after the installer is created and the app installed to C:\Program Files it throws the exception.  

### **Repro Steps**

1. Create the installer for the app (I've used InnoSetup).
2. Install the app to C:\Program Files without admin permissions.
3. Run the app.

![2019-08-14_17-58-38](https://user-images.githubusercontent.com/8818052/63033138-d5697500-bebf-11e9-9c49-8876dffd4f19.png)

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    WinForms
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
   .NET 4.6.1
2. Which SDK version are you using?
    2.2.1-preview
4. Which OS version did you experience the issue on?
   Windows 10
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    PC

**Comment by annakocheshkova** [comment]
Hi there @sanyandreichuk thank you for opening the request. I didn't manage to reproduce your issue so looks like the problem is with installer.
Usually in such a case, the problem is that the installer doesn't always require elevated permissions.
For instance, **InnoSetup** has a `PrivilegesRequired` property that only accepts always or never requiring admin and there seems to be no easy way to request it at a later point after selecting components.
There's also [this solution](https://stackoverflow.com/a/40717916/7453375) which seems to be the case for some people.
Could you try that and tell me if it helps. Thank you.

**Comment by AnastasiaKubova** [comment]
Hi @sanyandreichuk! We did manage to reproduce your issue. We created a bug about it.

**Comment by sanyandreichuk** [comment]
2.3.0-preview works fine. Thanks.

**Comment by russelarms** [comment]
Glad to hear that! Thanks for using App Center. Feel free to get back to us again on any issues/concerns!
