### ISSUE TITLE
AppCenter Crashes for UWP status?

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/appcenter-sdk-dotnet#1160]
Hello, I'm having some troubles in understanding what's the current status for AppCenter Crashes SDK for UWP as the current production NuGet package (2.1.1) doesn't seem to collect any crash (checked using Fiddler) and crashes collected by preview package (2.4.0-preview) don't seem to appear in the Crashes portal.

**Comment by Jamminroot** [comment]
Hey, @FrayxRulez, thanks for getting in touch.
The latest preview versions temporarily removed UWP crashes support, since our backend is not yet ready to process crashes collected from UWP.
We have this in [our plans](https://github.com/microsoft/appcenter/issues/1114), no ETAs I could provide yet though.
I'll address your request to our PMs team.

**Comment by winnieli1** [comment]
Hi @FrayxRulez  - we're making some improvements to our UWP support and ask that you use the non preview NuGet packages during this period. This will be complete in the next SDK release (2.5.0) later this month. 

Thanks!
