### ISSUE TITLE
UWP What is or isn't supported?

### ISSUE THREAD

**Issue by helzgate** [microsoft/appcenter-sdk-dotnet#1212]
At the bottom [of this page](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin) we see:

![2019-11-13 11_06_12-Get Started with Xamarin - Visual Studio App Center _ Microsoft Docs](https://user-images.githubusercontent.com/7506982/68787192-aff71f00-0606-11ea-94bd-cee02d74ad8f.png)

This appears to say that only Analytics works on Xamarin.UWP.  Is this true or do the docs need to be updated?

This is so confusing because half the time I can't tell if Microsoft means a native Xamarin UWP app or a Xamarin Forms app on UWP (maybe there is no difference, I don't know).  

Within a Xamarin.Forms UWP app can I do the following:
Log crashes to the AppCenter Console?
Distribute Updates Through AppCenter on a SideLoaded App?

**Comment by guperrot** [comment]
Hi,

Crashes API are now supported for UWP since version 2.5.0 of the nugets and this page thus should have been updated. I will forward the feedback.

UWP has support for Crashes, Push and Analytics.

Distribute in-app updates are not supported (https://docs.microsoft.com/en-us/appcenter/sdk/#windows-uwp). So the note is still accurate for the Distribute module (we just need to remove Crashes from that note).

There is no difference between UWP and Xamarin Forms UWP as far as platform/API support is concerned. The getting started has just slightly different instructions for where to put the start code when its Forms or non Forms.

**Comment by helzgate** [comment]
You answered every question.  Love it.  Thank you sir!
