### ISSUE TITLE
Microsoft.Azure.Mobile.Client.SQLiteStore and AppCenter 3.0.0

### ISSUE THREAD

**Issue by myokeeh** [microsoft/appcenter-sdk-dotnet#1349]
### **Description**

I have apps that depend on Microsoft.Azure.Mobile.Client.SQLiteStore and since AppCenter 3.0.0, there appears to be some SQLite related conflict I can't get past. I understand SQLiteStore is no longer being actively developed, but appreciate any guidance on how I can make my apps work with dependencies on both. AppCenter logging works, but the SQLite store cannot initialize with `"Method not found: 'System.String SQLitePCL.raw.sqlite3_errstr(Int32)'."`

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - UWP
2. Which SDK version are you using?
    - e.g. 3.0.0
4. Which OS version did you experience the issue on?
    - e.g. Windows 10 (1909, 2004)
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical devices
6. What third party libraries are you using?
   -Microsoft.Azure.Mobile.Client.SQLiteStore

**Comment by MatkovIvan** [comment]
Hi @myokeeh ,

App Center 3.0 uses SQLitePCLRaw v2 and not compatible with libraries that uses v1. For now, you can stay on 2.x to use these libraries together.

Related issues:
- #1340
- https://github.com/Azure/azure-mobile-apps-net-client/issues/533

Closing this issue, because there is updating SQLitePCLRaw in `Microsoft.Azure.Mobile.Client.SQLiteStore` feature request -  https://github.com/Azure/azure-mobile-apps-net-client/issues/533

**Comment by myokeeh** [comment]
Microsoft.Azure.Mobile.Client and Microsoft.Azure.Mobile.Client.SQLiteStore version 4.2.0 released today fixes this.
