### ISSUE TITLE
OutOfMemoryError in com.microsoft.appcenter.crashes.Crashes.saveUncaughtException

### ISSUE THREAD

**Issue by thisisthekap** [microsoft/appcenter-sdk-dotnet#1392]
### **Description**

Got OutOfMemoryError from Blade V6 Plus running Android 6.0. Issue was reported by AppCenter reporting.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Microsoft.AppCenter.Crashes 2.1.1 on Android.
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.1.
2. Which SDK version are you using?
    - 2.1.1
4. Which OS version did you experience the issue on?
    - Android 6.0
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Blade V6 Plus

**Comment by MatkovIvan** [comment]
Hi @thisisthekap,

I guess (since no logs attached) it's more "OutOfMemoryError thrown while trying to throw OutOfMemoryError".

Let me just quote the explanation from previous similar ticket https://github.com/Microsoft/AppCenter-SDK-Android/issues/900:

> So here's what happens: your app is using a lot of memory which causes an OOM (out of memory exception). The App Center SDK is catching that exception but since the app is already so low on memory that it received the OOM, the App Center SDK doesn't have enough memory to process it (and the SDK is already optimized to use as little of it as possible) and throws an OOM itself. (Think of it as OOM-ception if you will ;))
The bottom line is that it's not the App Center SDK itself that is crashing but the issue lies in the memory usage by the app.

The suggestion here is to monitor and optimize app's memory usage. I'm closing the issue since it doesn't seem SDK problem, but feel free to reopen/reply if you have more questions or additional info that we can investigate.
