### ISSUE TITLE
Access report ID

### ISSUE THREAD

**Issue by abdelrahman-alfar** [microsoft/appcenter-sdk-dotnet#1398]
**Is your feature request related to a problem? Please describe.**
We try to track the reportId to search easier on the appcenter when handling the exception we show a message box to our customers and we would like to include this reportID in the message.

at the begining tried to handle it using this event **Crashes.SentErrorReport** 
  private void Crashes_SentErrorReport(object sender, SentErrorReportEventArgs e)
        {
            var issueKey = e.Report.Id;
            this.showMessageService.ShowInfoBlocking(ErrorWindowStrings.PublishError, ErrorWindowStrings.SendErrorSuccessFormat(issueKey));
        }
but found out that this event is only triggered when the app crashes not when its handled

**Describe the solution you'd like**
You can return the report Id using   Crashes.TrackError(exception, properties, attachments) for example instead if its void

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! We will create a feature request for this.

**Comment by DmitriyKirakosyan** [comment]
Hi @abdelrahman-alfar ,

I would like to refresh the status of this feature request with you. Could you please confirm that this feature request is still relevant for you? If yes, please provide some information on how exactly you would like to use this reportId and if there are any alternatives/workaround which you are currently using instead.

**Comment by abdelrahman-alfar** [comment]
Hi @DmitriyKirakosyan 
I opened a pull request with it last year :) https://github.com/microsoft/appcenter-sdk-dotnet/pull/1401

**Comment by DmitriyKirakosyan** [comment]
Hi @abdelrahman-alfar , yep we are aware of your PR and that's why I'm reaching out to you. Sorry for being unclear in my message.
First of all, thank you so much for your contribution! I would like to know more about your use case to have a better understanding how much value it can bring to SDK users.
In case we decide to merge the changes in your PR, we would also need to update all other platforms (android native, apple native, xamarin, react-native, unity) for the sake of consistency. That is why I would like to know more about how this feature is going to be used.

**Comment by DmitriyKirakosyan** [comment]
Hi @abdelrahman-alfar , just a friendly ping.
Btw, as for searching a report for a specific user you can use an `userId` or a `sessionId`.

**Comment by DmitriyKirakosyan** [comment]
I'm going to close this feature request but feel free to reopen if anyone is still interested in it.
Will also close the PR for now.
