### ISSUE TITLE
Appcenter not working in China

### ISSUE THREAD

**Issue by sohailp07** [microsoft/appcenter-sdk-dotnet#1449]
### **Description**

When we are using our app inside China, appcenter is not reporting any activity, events, logs or crashes.
On investigating we could observe that our app was making **Tunnel** requests to **in.appcenter.ms**, it was responding with httpcode **200** but was _closing the connection from serverend_ 
**Error** - _HTTPS handshake to in.appcenter.ms (for #34) failed. System.IO.IOException Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. < An existing connection was forcibly closed by the remote host_

![image](https://user-images.githubusercontent.com/72014142/94417602-e5184b80-019d-11eb-84ed-79a8c698a2be.png)

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - UWP App.
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard code v.4.6.2.
2. Which SDK version are you using?
    - 2.6.4
4. Which OS version did you experience the issue on?
    - Windows 10 
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical devices located in China connected on China ISP

@guldagadan for more information and details

**Comment by virtualcca** [comment]
I also encountered the same problem
and then I tried to deploy my uwp program to a virtual machine in other places (such as Hong Kong)
 and found that the data can be uploaded. 
So I suspect that there is a problem with the Chinese mainland network accessing appcenter.

**Comment by lukeza** [comment]
I had the same issue. I saw the data stopped coming in from Sep 12th.

**Comment by vvechkanov** [comment]
HI!
We looked into this. It looks like this is not an SDK problem. It is more about the connection to a backend server. As we know, the backend team already knows about it. 
We can not do much with backend issues here. For such issues, you could contact the support team on https://appcenter.ms web page. You can do it by clicking "?" and selecting "contact support". They can help you with this, and may be find some temporary workaround.

I suggest we close it, by if you think this issue is in AppCente SDK code, or have some additional thoughts, feel free to reopen this issue.
