### ISSUE TITLE
Crash is not getting reflected in AppCenter when Appcenter starts in App.xaml.cs and Crash happening in Oncreate() method of Android

### ISSUE THREAD

**Issue by shreekantmundhe** [microsoft/appcenter-sdk-dotnet#1504]
I tried to start AppCenter in App.xaml.cs file and then in OnCreate() of Xamarin.Android I did crash using Crash.GenerateTestCrash(). But Crash logs are not reflecting in AppCenter, I checkde one things is that , My crahs in OnCreate() happen before AppCenter starts in App.xaml.cs.

Can someone please let me know this behavior.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!

It happens because `OnCreate()` method called early than `App()`. 
You can try to move the App Center start to the `OnCreate` method (see [here](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin#42-add-the-start-method)). But please pay attention that App Center SDK needs time for starting and if a crash happens before the complete start of App Center SDK the crash will not catch. You can check if App Center is enabled or not like [here](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#check-if-app-center-is-enabled).

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
