### ISSUE TITLE
Crashes because of DllImport

### ISSUE THREAD

**Issue by ranjan-2209** [microsoft/appcenter-sdk-dotnet#1524]
Can we have a feature where we can have crash analytics in AppCenter because of `DllImport `?

**Comment by russelarms** [comment]
@ranjan-2209 I moved it to the .NET repository so we can keep track of this feature request appropriately, but we don't have an ETA for it yet.

At the moment you can try-catch those exceptions manually and send them to AppCenter
https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms
`The App Center SDK collects only crashes caused by unhandled .NET exceptions. It doesn't collect native crashes e.g. when using C or C++. However, if you have an app with C++ crashes, you can upload them to App Center via the upload crashes API.`

**Comment by ranjan-2209** [comment]
ok, Thanks.
Pls close this issue if appropriate

**Comment by l16659** [comment]
Hello, I want to add appcenter to my macos binary project, but my code is written in pure c++. I've been looking for a long time but I can't find the right tutorial or appcenter sdk. Can someone help me? (My whole project also includes c#, oc, oc I have implemented appcenter)

**Comment by DmitriyKirakosyan** [comment]
Hi @l16659 , Unfortunately, the App Center SDK does not support C++ projects, and we don't have plans to include this support in the coming year.

However, for DotNet C# projects, you can refer to this [documentation](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin).
