### ISSUE TITLE
Migrate to System.Text.Json

### ISSUE THREAD

**Issue by tipa** [microsoft/appcenter-sdk-dotnet#1588]
System.Text.Json appears to be Microsofts new library for handling JSON. Some libraries from Microsoft are already using it (e.g. the Microsoft Graph .NET SDK).

Are there any plans for migrating the AppCenter SDK to System.Text.Json?
This would be appreciated, not only because of the better (de)serialization performance that System.Text.Json offers, but also because of lesser dependencies needed, making my app's binaries smaller.

**Comment by DmitriyKirakosyan** [comment]
Hi @tipa, thank you for bringing this idea to our attention!

It is a good point! I'll create a feature on our board.
The only issue with the migration that I can see now is that we support some dotnet versions which `System.Text.Json` doesn't support, for example .NET Framework 4.6.1 for [WPF](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms#1-prerequisites). We will need to still use `Newtonsoft.Json` for such unsupported versions.

**Comment by tipa** [comment]
Thanks a lot for considering!

> for example .NET Framework 4.6.1 for [WPF](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms#1-prerequisites)

I've read that .NET Framework 4.6.1 [will reach End-off-support early next year](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/). Maybe that makes the decision easier ;)

**Comment by DmitriyKirakosyan** [comment]
Yep, I was thinking about the this thing too :)

**Comment by michaldobrodenka** [comment]
I think .NET Framework 4.6.1 supports .NET Standard 2.0 which is targeted by System.Text.Json. And System.Text.Json has a profile for .NET Framework 4.6.1

**Comment by aleksandr-dorofeev** [comment]
Thanks for the information @michaldobrodenka 
We will take this into account when we do feature.

**Comment by laolarou726** [comment]
That will be so great if port the Newtonsoft.JSON to System.Text.Json! How's the progress right now?

**Comment by tipa** [comment]
@DmitriyKirakosyan Are there any updates and/or would you accept pull requests for this?

**Comment by MatkovIvan** [comment]
@tipa it's in our queue after proper .NET 6 support. No exact ETA yet.

Of course contributions are welcome here

**Comment by tipa** [comment]
I checked out the repo and spent multiple hours trying to successfully build the library, without success. It constantly complains about missing references. No idea how this is supposed to work.
The actual JSON-bits were easily replaced, but without being able to test them, a PR doesn't make much sense.

**Comment by Panda-Sharp** [comment]
@MatkovIvan any update on this? thanks!

**Comment by mihaimihaila** [comment]
As the original poster mentioned, Microsoft’s own guidance is to migrate from `Newtonsoft.Json` to `System.Text.Json`. This is not only because of the improved (de)serialization performance that `System.Text.Json` offers, but also because it aligns with Microsoft’s own best practices.

Furthermore, the reduction in dependencies would lead to smaller binary sizes for our apps, which is a significant advantage, especially for mobile applications where every byte counts. This migration would make our apps leaner and more efficient.

Given that this request was made back in November 2021 and it’s now February 2024, I believe it’s high time for this migration to take place. Let’s make our apps better by embracing `System.Text.Json`!

Thank you for considering this request. I look forward to seeing the **AppCenter SDK** continue to improve and evolve.

**Comment by MikhailSuendukov** [comment]
Hi, currently, we do not have plans for this migration. However, we highly value and welcome your contributions.

**Comment by Panda-Sharp** [comment]
Do you have any plan for the appcenter-sdk-dotnet in general?
