### ISSUE TITLE
AppCenter do not send data when target .net framework 4.6.1

### ISSUE THREAD

**Issue by optimodzhu** [microsoft/appcenter-sdk-dotnet#1650]
AppCenter cannot recieve events

Hello! AppCenter is said support .net framework 4.6.1 in this document, and it did work one years ago. But recently I found it can not send data when target net461. It is also occurs when I create a new project and add AppCenter reference only. After I changed target to net 471 or higher, AppCenter works as expected. It is confusing! 
My computer OS is windows 11 21H2.
Tested AppCener Versions are 4.5.1, 4.5.0, 4.4.0.
Bset regards!

Hello!, I have test again. Following the guidance, I have created three wpf projects targeting net461, net472, net6.0. But none of them sent data successfully, leaving AppCenter dashboard blank. I do not know where I was wrong.

![Screenshot](https://user-images.githubusercontent.com/46378395/171528913-29ae19eb-d547-4bde-bc70-02ee81f75a2a.jpg)

My code is here:
[Test.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/8819799/Test.zip)

I test them respectively, but only net6.0 version generate log.db:
[Logs.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/8819829/Logs.zip)

**Comment by AlexeyBudynkov** [comment]
Hello. What do you mean by sending data?

**Comment by optimodzhu** [comment]
> Hello. What do you mean by sending data?

AppCenter dashboard cannot recieve errors or events from app with .net framework 4.6.1, wpf or winform.

**Comment by AnatolyPristensky** [comment]
Hello @optimodzhu,
Could you please share some logs and describe issue more precisely?

**Comment by optimodzhu** [comment]
> Hello @optimodzhu, Could you please share some logs and describe issue more precisely?

OK, I will do that.

**Comment by DmitriyKirakosyan** [comment]
Hi @optimodzhu , I saw you updated the description with the links. However, the file `Test.zip` is not available. Please check if the link is correct. You can attach the file in a comment.

Also, regarding this issue, have you tried to send custom events using `Analytics.TrackEvent`? Would it work?

**Comment by DmitriyKirakosyan** [comment]
Hi @optimodzhu , I've checked your test project and it turned out you had namespace issues in it. dotnet framework 461 and 472 based projects had namespace `Test60` (from .net 6.0 project). Given that, the projects didn't compile correctly and the App.xaml.cs's `OnStartup` was never called, and thus app center was not initialized.

I've fixed this issue in your project and everything started working, please check the attached file.
[Test.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/8878464/Test.zip)


However, please note that there is a known bug in AppCenter SDK 4.5.1, the StartSession event is not sending which makes some data unavailable on the Analytics page. Custom events are still successfully sending though. To work around this bug, use SDK 4.5.0.

I'm closing this issue, but feel free to reopen if you have additional questions.

**Comment by optimodzhu** [comment]
> Hi @optimodzhu , I've checked your test project and it turned out you had namespace issues in it. dotnet framework 461 and 472 based projects had namespace `Test60` (from .net 6.0 project). Given that, the projects didn't compile correctly and the App.xaml.cs's `OnStartup` was never called, and thus app center was not initialized.
> 
> I've fixed this issue in your project and everything started working, please check the attached file. [Test.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/8878464/Test.zip)
> 
> However, please note that there is a known bug in AppCenter SDK 4.5.1, the StartSession event is not sending which makes some data unavailable on the Analytics page. Custom events are still successfully sending though. To work around this bug, use SDK 4.5.0.
> 
> I'm closing this issue, but feel free to reopen if you have additional questions.

Thank you very much!
