### ISSUE TITLE
Restore 4.4.0 package to nuget

### ISSUE THREAD

**Issue by Pastajello** [microsoft/appcenter-sdk-dotnet#1672]
Hello,

first question why was 4.4.0 package removed from nuget? Was there some super security risk there?
![image](https://user-images.githubusercontent.com/28345098/185360814-5bd42508-fbdd-41df-b2ef-0c4fbe0d27e9.png)

My project had some problems and we wasted some hours wondering what was happening and all it was MS decided to delete a version.

**Comment by MatkovIvan** [comment]
Hi @Pastajello,

This version was marked as outdated (to warn users) and after some time unlisted fully due to NuGet team request because of P0 restoring loop issue. See details and explanation [here](https://developercommunity.visualstudio.com/t/Package-Manager-does-not-stop-restoring/10043518).

Sorry for inconvenience
