### ISSUE TITLE
Unable to use Xamarin Forms previewer with Mobile Center SDK

### ISSUE THREAD

**Issue by robertmiles3** [Microsoft/AppCenter-SDK-DotNet#496]
I just recently added the Mobile Center SDK to my Xamarin Forms app, then realized it broke Xamarin Forms previewer for my forms pages. The exception is...

```Could not create an native instance of the type 'Microsoft.Azure.Mobile.iOS.Bindings.MSWrapperSdk': the native class hasn't been loaded.```

I can't copy the full error, so here's a screenshot...

![image](https://user-images.githubusercontent.com/944302/32792746-25a60ee6-c932-11e7-88f8-8fd381f52db6.png)

Visual Studio for Mac: 7.3 build 740
Xamarin Forms: 2.4.0.74863
Mobile Center SDK: 0.17.1

**Comment by achocron** [comment]
Hi- are you starting Mobile Center in the OnStart method, or App constructor?

**Comment by robertmiles3** [comment]
in `App.xaml.cs` ctor, per https://docs.microsoft.com/en-us/mobile-center/sdk/getting-started/xamarin#423-xamarinforms

**Comment by guperrot** [comment]
Hi, can you try moving initialization code for `MobileCenter.Start` and other related calls to `OnStart` instead?

**Comment by robertmiles3** [comment]
@guperrot Seems to work ok if I put it in `OnStart` instead. Given the docs say the constructor, is `OnStart` a viable solution long-term?

**Comment by guperrot** [comment]
@robertmiles3 the docs is a getting started that needs to be very simple. We don't discuss all the details in getting started and basically you could call Start wherever you want, and we didn't notice the problem with previewer before. We used to document OnStart in the past and wanted init to happen sooner for Crashes to catch crashes earlier (and to align with UWP non Forms apps).

We will switch back the docs to OnStart just because of the previewer (it cannot load native code), but keep in mind that its just a rule of thumb.

**Comment by robertmiles3** [comment]
@guperrot Gotcha, thanks. I'll leave it in `OnStart`. Feel free to close this out if you want.
