### ISSUE TITLE
SDK communications with unsecure server in.appcenter.ms (TLS 1.0)

### ISSUE THREAD

**Issue by MisterJimson** [Microsoft/AppCenter-SDK-DotNet#647]
### **Description**

The SDK communicates with a domain that supports TLS 1.0. TLS 1.0 is no longer considered secure and after a security review of our mobile application, we have been told that our app cannot speak to any domains that support TLS 1.0.  

### **Repro Steps**

Use the SDK and observe that it communicates to in.appcenter.ms.
Use a website like ssl labs to check supported TLS versions. https://www.ssllabs.com/ssltest/analyze.html?d=in.appcenter.ms&latest

I've removed the details questions since they are irrelevant.

**Comment by TroubleMakerBen** [comment]
Hi @MisterJimson,

Thx for getting in touch. If TLS 1.2 is available on a device, we will use that. Our Android SDK supports Android versions < 4.4. Those devices don't support TLS 1.2, so we have 1.0 around for backward compatibility only.

**Comment by guperrot** [comment]
Version [1.7.0](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.7.0) enabled TLS 1.2 on API level 16+ instead of 20+.

On the current version of the SDK, only devices with API level 15 are still using TLS 1.0.

Next version (1.10.0) will drop support for API level 15 and TLS 1.2 will be enforced server side soon.

**Comment by MatkovIvan** [comment]
Version [1.10.0](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.10.0) is released.
