### ISSUE TITLE
How to prevent potential analytics secret key theft when it is stored on the app side?

### ISSUE THREAD

**Issue by hashamrashid** [Microsoft/AppCenter-SDK-DotNet#761]
Hi

The Analytics functionality requires the app secret key to be stored on the app.

**This seems to be a potential security hazard as keys can be easily decompiled/intercepted.**

To prevent this, we could just track the events from the server side , i.e. device sends the data to the backend server and the server then sends it to appcenter.

However, using the standard method to add appcenter to a web api project:

  **AppCenter.Start("SECTETKEYHERE", typeof(Analytics));**
And then tracking the event this way
**Analytics.TrackEvent("MyTestEvent",new Dictionary<string, string>{{"EventNameHere","EventValueHere"}});**
No event data ever arrives in the appcenter dashboard.

So my question is , how do I use the trackevent functionality on the serverside, or , at the very least, store the key on the app side securely(I'd really rather not do this).

Thanks

**Comment by clpolet** [comment]
Hi @hashamrashid.
There is no way to be 100% secure about the "AppSecret", this is why it just really is a token, if it gets compromised then we'll generate another one but yes you'll then have to update your application. 
_"device sends the data to the backend server and the server then sends it to appcenter."_ In this scenario the backend server would also need a token so only your app could use its API, same issue.
Instead you can have your CI/build system inject your AppSecret into your code via an environment variable so that at least the AppSecret is not in clear in the code.

I am not really sure it answers your question let me know otherwise.

**Comment by ElektrojungeMS** [comment]
Hey @hashamrashid,

We haven't heard from you in a while so I'm going ahead and close this issue but feel free to reply/reopen or get in touch through Intercom (blue button on the website) so we can discuss your concerns.

Best,
Benjamin

**Comment by MikeyFriedChicken** [comment]
So it's not really a secret? Every app store app would be exposing this token right?

**Comment by vvechkanov** [comment]
Hi @MikeyFriedChicken!
Not necessary, you could hide your appsecret,  using environment variable on CI/CD for example. There is a [doc](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/android#protect-the-app-center-secret-value), in appcenter documentation, describing how appsecret could be hidden and what are the risks of it exposing.
Please take a look at it. Feel free to ask additional questions if the article does not answer all of your questions.
