### ISSUE TITLE
[Android] ssl issues when tracking 

### ISSUE THREAD

**Issue by bentmar** [Microsoft/AppCenter-SDK-DotNet#795]
https://github.com/Microsoft/AppCenter-SDK-Android/issues/917

Created an issue on the android side of this. but since im using the xamarin lib i thought i would fit here aswell

**Comment by guperrot** [comment]
@bentmar Please try this prerelease nugets to see if that fixes the issue [microsoft.appcenter.1.12.1-r0003-63f5bc0.zip](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2725728/microsoft.appcenter.1.12.1-r0003-63f5bc0.zip).

None of our kitkat devices have the issue so we'd like you to confirm if the issue is fixed with those preview nugets.

**Comment by bentmar** [comment]
Tested it now and it works :)

**Comment by guperrot** [comment]
That's good news, we will include the fix in the next release then.

**Comment by guperrot** [comment]
The fix is now included in the version [1.13.0](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.13.0) of the nugets.
