### ISSUE TITLE
Logging in for in-app updates

### ISSUE THREAD

**Issue by VladRaven5** [Microsoft/AppCenter-SDK-DotNet#844]
Hello!
We are going to migrate our Xamarin.Android app from HockeyApp to AppCenter. But in-app distribution forces our customers and testers visit AppCenter login page, what is **highly** undesirable in our workflow. Is there any workarounds to avoid logging in or made it implicit for users (i.e. silently process logging in app)?
Thanks!

**Comment by amrutha786** [comment]
@VladRaven5 , If I understood the question right, when ever the user scans the QR Code he is taken to a AppCenter Login Page, Is it right? I had the same issue but I have created a public group to allow any device registered in that provisioning profile to download with out login. 
Have you considered enabling that one?

**Comment by VladRaven5** [comment]
@amrutha786, not exactly.
When the user installs our app from an APK and runs it first time, browser with AppCenter login page is automatically opened. If the user decline logging in, in-app update doesn't work (new version popup doesn't appear).
We tried distribute the app through public distribution group, but behavior the same.

**Comment by kvpt** [comment]
This issue is very problematic for us too.
If you use an apk directly it doesn't work, it request the user to login.
The only way which doesn't require a login is using the link from the public distribution group from the browser. I think it set a cookie in the browser and in that case only the browser allow anonymous mode.
It's a breaking change compared to HockeyApp where distribute the downloaded apk doesn't require a login at all.

**Comment by guperrot** [comment]
Yes, to avoid logging in you need the releases to be distributed in a group which has the public option.
Then you can share the public distribution URL to your testers and they have to install it from that URL (which does not require login).

If they did install via the public url, the SDK will open browser but without login prompt and redirect back to the application on the first launch.

**Comment by kvpt** [comment]
It need to be possible to not have to login.

Consider this case, we have 500 installations of an app deployed with HockeyApp and we want to migrate then on AppCenter.
1. We create the App on AppCenter and create a public distribution canal
2. We migrate the HockeyApp SDK to AppCenterSDK in the app (and change the app id to the app created in AppCenter)
3. We deploy the updated application in HockeyApp
4. The users get the update via HockeyApp (which migrate the distribution system to AppCenter)
5. We deploy the next update in AppCenter
6. The user get the update via AppCenter

But it doesn't work, because in the step 5, the app is not retreived by the web browser (so no cookie) and after when the app launch, the user have to login to enable update.
But with HocheyApp they doesn't and haven't account, so too be in parity with HockeyApp, it need to have a distribution mode that doesn't require login at all (without to pass by a web browser earlier).

**Comment by Oddj0b** [comment]
Thank you for reporting the bug, I am actively looking into how we can fix it.

Sorry for the inconvenience.

**Comment by Oddj0b** [comment]
I have created a bug in our public repo to track it in one place. 
https://github.com/Microsoft/appcenter/issues/182

**Comment by kvpt** [comment]
Thanks you @Oddj0b ,

For now we can continue to use HockeyApp so we can wait but it's critical that this issue is resolved before HockeyApp shutdown.

**Comment by guperrot** [comment]
Since this is not specific to the .NET SDK, please use https://github.com/Microsoft/appcenter/issues/182 for additional comments and discussion on that topic.
